# Generated by Django 3.1.7 on 2021-05-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('manufacturer', models.CharField(max_length=50)),
                ('manufacturer_part_number', models.CharField(max_length=50)),
                ('supplier', models.CharField(max_length=50)),
                ('supplier_part_number', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
